labels:
  - label: 'Type: Bug'
    title: '^fix(.*'
  - label: 'Type: Documentation'
    title: '^docs(.*'
  - label: 'Type: Feature'
    title: '^feat(.*'
  - label: 'Type: Infrastructure'
    title: '^build(.*'
  - label: 'Type: Infrastructure'
    title: '^ci(.*'
  - label: 'Type: Technical'
    title: '^chore(.*'
  - label: 'Type: Technical'
    title: '^perf(.*'
  - label: 'Type: Technical'
    title: '^refactor(.*'
  - label: 'Type: Technical'
    title: '^revert(.*'
  - label: 'Type: Technical'
    title: '^style(.*'
  - label: 'Type: Technical'
    title: '^test(.*'
